### ISSUE TITLE
Update to 1.5.0

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.freedesktop.Platform.Icontheme.Paper#3]
This extension hasn't been updated in a while and there's a much more recent release now available: https://github.com/snwh/paper-icon-theme/releases/tag/v.1.5.0

**Comment by nedrichards** [comment]
I have a feeling that this being old causes this crash: https://github.com/flathub/com.visualstudio.code/issues/61

**Comment by TingPing** [comment]
That crash does show the *host* path though, not the extension path.

**Comment by nedrichards** [comment]
You're right.
