### ISSUE TITLE
How to build this in Gnome Builder?

### ISSUE THREAD

**Issue by unholyeyebrows** [flathub/org.freedesktop.Platform.Icontheme.Paper#4]
Hi

I'm trying to build this into a Flatpak using Gnome Builder as I want to us this as a template to build a similar package for the Newaita icon theme for personal use. However having imported the three files into Builder nothing happens when I click 'build'.

I am new to making Flatpaks in Builder so I may be missing something obvious, so any help on this would be appreciated.

Thanks
Nick

**Comment by jurf** [comment]
I think the way Builder works is it replaces the source for the tree it is running in, but this isn’t really an app, you don’t have anything to launch. I think you’d be better off using classic [flatpak-builder](http://docs.flatpak.org/en/latest/building-introduction.html).

**Comment by unholyeyebrows** [comment]
Thanks. I have indeed managed to build it using flatpak-builder so that helps me a lot. I'll close this off now.
